/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    LogPanel: typeof import('./src/components/LogPanel.vue')['default']
    ThreeViewport: typeof import('./src/components/ThreeViewport.vue')['default']
  }
}
